title: Danny Smilie
logo: "/images/GitHub portfolio profile picture - blue border.png?raw=true"
description: |
  Analytics, Partnerships, and SaaS sales. My background is in identifying areas for improvement within strategic partnerships and sales, using data to inform my decision making, and taking initiative to solve problems and improve my area of the business. 
  <br><br>
  <a href="https://www.linkedin.com/in/danny-smilie/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
