title: Danny Smilie
logo: "/images/GitHub portfolio profile picture - blue border.png?raw=true"
description: |
  Analytics, Partnerships, and SaaS sales. My background is in identifying areas for improvement within strategic partnerships and sales, using data to inform my decisions, and executing on the changes required to improve partnerships and sales outcomes. 
  <br><br>
  <a href="https://www.linkedin.com/in/danny-smilie/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
