title: Danny Smilie
logo: "/images/GitHub portfolio profile picture - blue border.png?raw=true"
description: |
  <br><br>
  <a href="https://www.linkedin.com/in/danny-smilie/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
